# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

divide <- function(x, y) {
    .Call(`_fdesigns_divide`, x, y)
}

bs2intcpp <- function(j, t, pbeta, px, dbeta, dx, ex_lambdabeta, ex_lambdax) {
    .Call(`_fdesigns_bs2intcpp`, j, t, pbeta, px, dbeta, dx, ex_lambdabeta, ex_lambdax)
}

bs2jcbcpp <- function(t, dbeta, dx, knots_beta, knots_x) {
    .Call(`_fdesigns_bs2jcbcpp`, t, dbeta, dx, knots_beta, knots_x)
}

bsintcpp <- function(j, p, degree, exl, t) {
    .Call(`_fdesigns_bsintcpp`, j, p, degree, exl, t)
}

jcbfunccpp <- function(db, degree, knots, t) {
    .Call(`_fdesigns_jcbfunccpp`, db, degree, knots, t)
}

Vpowercpp <- function(db, tu) {
    .Call(`_fdesigns_Vpowercpp`, db, tu)
}

bsallintcpp <- function(t, j, nbs, allpos, alldeg, exknots) {
    .Call(`_fdesigns_bsallintcpp`, t, j, nbs, allpos, alldeg, exknots)
}

bsplinesecderprodcpp <- function(t, degree, pos, knots) {
    .Call(`_fdesigns_bsplinesecderprodcpp`, t, degree, pos, knots)
}

Vbsplinecpp <- function(db, tu, knots) {
    .Call(`_fdesigns_Vbsplinecpp`, db, tu, knots)
}

bsalljcbcpp <- function(t, j, nbs, aposx, alldeg, allknotsxb, nx, nb) {
    .Call(`_fdesigns_bsalljcbcpp`, t, j, nbs, aposx, alldeg, allknotsxb, nx, nb)
}

bsalljcbpowercpp <- function(t, j, nbs, aposx, alldegx, allknotsx, nx, nb) {
    .Call(`_fdesigns_bsalljcbpowercpp`, t, j, nbs, aposx, alldegx, allknotsx, nx, nb)
}

